class BUCK_COMPONENT(object):
    (ACTIVE_MOS,PASSIVE_MOS,INDUCTOR) = range(0,3)

class DCX_COMPONENT(object):
    (PRIMARY_MOS,SECONDARY_MOS,TRANSFORMER) = range(0,3)

class TWO_TER_TRANSFORMER(object):
    (PRIMARY_WINDING,SECONDARY_WINDING) = range(0,2)

MAX_ITER_NUM = 100